name: NOR

on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Windows
        - Ubuntu
        - macOS

jobs:
  test:
    runs-on: ${{ inputs.chosen-os }}-zrunner
    steps:
    - run: echo Hello world!
